### ISSUE TITLE
Crash when selecting a subtitle file

### ISSUE THREAD

**Issue by sp3ctum** [lrorpilla/jidoujisho#13]
I have an anime episode and subtitles for that episode as an `.ass` file. When I select "Load External Subtitles" from the player menu and select that `.ass` file, the player crashes every time.

I seem to be able to work around this crash if I first select "no subtitles" and then select the `.ass` file.

I suspect this may have something to do with the fact that the video file has an embedded English subtitle that is selected by default.

I'm using the latest version, 0.13.1 beta.

I realize this is not a lot to go by, so let me know what I could provide to help investigating this.

**Comment by sp3ctum** [comment]
It seems the workaround I described is not that reliable... A better workaround seems to be to start playing a different file and then switch back to the first file.

Looks like it tries to load the subs that have the same name dna the extension but they are empty (the transcript is empty) but when I manually load the subs, they work fine.

This is a bit messy, maybe multiple issues occurring at the same time.

**Comment by lrorpilla** [comment]
I have a guess at the cause but to confirm the issue, please attach the subtitle file so I can have a look at it.

Cheers.

**Comment by sp3ctum** [comment]
Here is one of the files I have had problems with,

[[Doki] Usagi Drop - 02 (1920x1080 Hi10P BD FLAC) [94E10265].ass.zip](https://github.com/lrorpilla/jidoujisho/files/6371466/Doki.Usagi.Drop.-.02.1920x1080.Hi10P.BD.FLAC.94E10265.ass.zip)

**Comment by lrorpilla** [comment]
I have implemented a fix for this in [0.13.5](https://github.com/lrorpilla/jidoujisho/releases/tag/0.13.5-beta).

**The issue was that the code for loading the default subtitles assumed that the format was in SRT.** Therefore, any ASS files could not be loaded by default -- when importing them, the file was converted appropriately.

I also fixed an issue with subtitles where timestamps may occur due to a format issue.

See the relevant lines in the release notes:
* **Fixed an issue with default ASS/SRT subtitles** with the same filename as the video file were loaded as a raw string SRT
* **Fixed an SRT parsing issue which showed timestamps** in the transcript where the line after the timestamp showed up as blank

I am closing this issue. If this issue persists, please do report and I will reopen this issue.

**Comment by sp3ctum** [comment]
Unfortunately this is still occurring for me.

Before the new version, I would see the embedded English ass subs as well as the Japanese ass subs that are in a file with the same name as the video.

After the fix, I only see the English subs in the subtitle selection menu.

In both cases, loading the Japanese subs as an external sub will crash or close the application.

**Comment by lrorpilla** [comment]
After investigations, I believe that this issue is an extremely low-end device-specific issue. I can't do much about it except to suggest sourcing the video and subtitles elsewhere -- the video and subtitle in question appear to load in multiple devices and emulators I have tested with. 

If ever more information arises, I may look over this again but for now I am closing this issue.
