### ISSUE TITLE
inaccurate or responsive selection of words in ebook feature

### ISSUE THREAD

**Issue by JunkyardCat** [lrorpilla/jidoujisho#133]
so i have tried to select words in jidojisho's ebook reader and its soo hard to select anything and if selected it either selected the next letter or nothing at all. I just have 2 dict installed. 1 ja-en and 1 ja-ja dict
i tried the same ebook on typhon kai and it works so good ( using default dict)

will you be improving the ebook part in the future?

**Comment by lrorpilla** [comment]
This issue is fixed in **[2.2.9](https://github.com/lrorpilla/jidoujisho/releases/tag/2.2)**. The reference for the fix can be found here and the JavaScript I've modified is **[here](https://github.com/lrorpilla/jidoujisho/blob/f6cfc8d1ecc9a871b8309b77fbb3b5f8ea248ae3/yuuna/lib/src/pages/implementations/reader_ttu_source_page.dart#L449-L640)**. I've tested this to work in Chrome with small and large font sizes and it appears to work.

**Comment by JunkyardCat** [comment]
now the dictionary doesn't even load anything. it just shows a black box then No search results found inside it with a magnifying glass. i tap on a word i had tapped before but it still shows just a black box as i described earlier

**Comment by lrorpilla** [comment]
Did you go from a fresh installation or from another version?

**Comment by JunkyardCat** [comment]
i updated from 2.1 to 2.2.3 to 2.2.9

**Comment by lrorpilla** [comment]
There was a breaking change to fix a bug in 2.2.7 where the dictionary database and other objects were moved to a different file location, so when you updated, this appeared to clear your dictionary. Sorry for the inconvenience.

**Comment by JunkyardCat** [comment]
@lrorpilla 
where is the place my old dictionary that it moved to? i just wanna make sure i delete it so i can save on space.

**Comment by lrorpilla** [comment]
It's stored in your applications support directory under `/data/user/0/app.lrorpilla.yuuna/isar`

**Comment by JunkyardCat** [comment]
@lrorpilla 
is isar a file or folder? i cant find the folder isar. please see below screenshot
![screenshot of directory](https://user-images.githubusercontent.com/22941307/211996710-da978611-e89b-450e-af28-18ca277d10a3.png)

**Comment by lrorpilla** [comment]
Should be under `files`

**Comment by JunkyardCat** [comment]
theres only default.isar file and default.isar.lock. it doesnt seem to be the dictionary files. 
![screenshot of jidojisho direcory 02](https://user-images.githubusercontent.com/22941307/211998927-c753775e-1583-42a6-87f1-baad8073d5ad.png)

**Comment by lrorpilla** [comment]
**[The following version](https://drive.google.com/file/d/135TT9xFnrjbFThoPJ-22QdFDBdN0uYxQ/view?usp=share_link)** should delete the directory automatically for you. Should work in the meantime.

**Comment by JunkyardCat** [comment]
ok thanks. ill wait for the release

**Comment by lrorpilla** [comment]
The link hyperlinked above is already uploaded so you can already download it.

**Comment by lrorpilla** [comment]
I've released 2.2.10 officially, and this issue is resolved, so I am closing this issue.
