### ISSUE TITLE
Audio stops working for a sentence or two 

### ISSUE THREAD

**Issue by Shudhanshu-Raj** [lrorpilla/jidoujisho#225]
version 2.6.1

When a dictionary lookup is active, changing the video's state so pausing or playing video results in the audio not working for some seconds, the only fix is rewinding or waiting that bit.
it's most likely a bug

**Comment by lrorpilla** [comment]
Can't reproduce this. Can you demonstrate with a video?

**Comment by lrorpilla** [comment]
2.6.1 is very, very outdated. Audio lag is an issue fixed in #198.

**Comment by lrorpilla** [comment]
I believe if you update to the latest version, you will get the fix for this -- this was fixed in one of the 2.6 hotfixes. If you can provide evidence that this is happening in 2.7, I would be open to looking at this again.

Closing as this is a duplicate of #198, which is already resolved.

**Comment by Shudhanshu-Raj** [comment]
Yes, I updated and the issue happens less often but still persists, I am kinda busy right now, I will upload a video of it happening later.

**Comment by Shudhanshu-Raj** [comment]
Also I don't think this should receive its own thread but another issue is that sometimes sentences do not export but most times it is exported, I can't see a pattern for it either

**Comment by lrorpilla** [comment]
If you've seen improvement, that's as much as I can do -- that's simply how VLC's audio drivers on Android are and I can't do anything about it really.

**Comment by lrorpilla** [comment]
If you're missing sentences, it's possible that you're mining them when they have already ended if you're watching video. If you provide reproduction steps and attach images and audio in your reports, that would be helpful for me to get down to fixing issues as soon as possible.
