### ISSUE TITLE
Subtitle and cut off audio 

### ISSUE THREAD

**Issue by haibaraaiesraa** [lrorpilla/jidoujisho#325]
Thank you for a wonderful App 🤩
This perhaps a problem from my side but I have to open the external subtitles everytime I open the video .. and the sentence audio usually is cutoff in the middle of the sentence even after timing the subtitle?

**Comment by HoanPiTa** [comment]
Yeah. It also my problem bro. Hope dev can understand this

**Comment by HoanPiTa** [comment]
Hi bro. I have same problem with mpv scripts and i fixed it.
The audio export is full but the audio you listen will not full.
You should pause at the start of next subtitle, so we will listen full audio
Hope Dev will fix it soon. I really like this app. It really useful

**Comment by sorata225** [comment]
>You should pause at the start of next subtitle, so we will listen full audio

Are you pausing it and clicking "Create Card from Context" @HoanPiTa ?

fyi, you can just click on the word in the subtitle and click on instant export in the dictionary pop up. Maybe the issue is specific to "Create Card from Context".

**Comment by haibaraaiesraa** [comment]
@sorata225 

> fyi, you can just click on the word in the subtitle and click on instant export in the dictionary pop up. Maybe the issue is specific to "Create Card from Context".

I click on the word normally and I still have the problem .

**Comment by haibaraaiesraa** [comment]
?🥲
